/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <gpio.h>

int prgm_state = OFF;

int main(void)
{


	gpio_init();

    /* Loop forever */
	for(;;){
		//nigg
		//led_toggle();
		prgm_state_set(&prgm_state);
		prgm_state_dsply(&prgm_state);

	}
}
