/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio.h"
#include "adc.h"
#include "usart.h"


int prgm_state = OFF;

char buff[64];
char adc_value;

int main(void)
{


	gpio_init();
	usart2_init();
	adc_init();
	adc_conversion();

    /* Loop forever */
	for(;;){
		led_toggle();

		prgm_state_set(&prgm_state);
		prgm_state_dsply(&prgm_state);
		led_delay();

		prgm_state_loop();

		adc_sample_signal(buff, &prgm_state);
		adc_value = buff;

	}
}
