/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//include library
#include "stm32f4xx.h"

int main(void){

	//RCC - advance high performance bus enabling GPIO pot A pin 6,7,8, port B pin 10, and port C pin 7
	RCC -> AHBENR |= RCC_AHBENR_GPIOAEN;
	RCC -> AHBENR |= RCC_AHBENR_GPIOBEN;
	RCC -> AHBENR |= RCC_AHBENR_GPIOCEN;

	//setup control registers for LED output
	//mode register for output
	GPIOA -> |= GPIO_MODER_MODER8_0;
	GPIOC -> &= ~(GPIO_MODER_MODER8_1);
	//output type register

	//speed register
	//pull up pull down register


	//Setup control register for push button input
	//mode register for input
	//pull up pull down



	while(1){
		//if the button is pressed (IDR - input data register)
		// turn on the LED (BSRR)

		// if the button is not press
		//turn off the LED (BRR)
	}
}

