/*
 * base.h
 *
 *  Created on: Jun 15, 2026
 *      Author: ryzel
 */

#ifndef BASE_H_
#define BASE_H_

/* reference manual - register boundary address */
#define PERIPHERAL_BASE 			(0x40000000)

#define APB1_PERIPHERAL_OFFSET 		(0x00000000)
#define APB1_PERIPHERAL 			(PERIPHERAL_BASE + APB1_PERIPHERAL_OFFSET)

#define APB2_PERIPHERAL_OFFSET 		(0x00010000)
#define APB2_PERIPHERAL 			(PERIPHERAL_BASE + APB2_PERIPHERAL_OFFSET)

#define AHB1_PERIPHERAL_OFFSET 		(0x00020000)
#define AHB1_PERIPHERAL 			(PERIPHERAL_BASE + AHB1_PERIPHERAL_OFFSET)

#define AHB2_PERIPHERAL_OFFSET 		(0x50000000)
#define AHB2_PERIPHERAL 			(PERIPHERAL_BASE + AHB2_PERIPHERAL_OFFSET)

/* Refer to block diagram in datasheet */
/* ADC connected to APB2 */
#define ADC_PERIPHERAL_OFFSET 		(0x00002000)
#define ADC_PERIPHERAL				(APB2_PERIPHERAL + ADC_PERIPHERAL_OFFSET)

/* USART2 connected to ABP1 */
#define USART2_PERIPHERAL_OFFSET 	(0x0000BC00)
#define USART2_PERIPHERAL 			(APB1_PERIPHERAL + USART2_PERIPHERAL_OFFSET)

/* connected to AHB1 */
#define GPIOA_PERIPHERAL_OFFSET 	(0x00000000)
#define GPIOA_PERIPHERAL 			(AHB1_PERIPHERAL + GPIOA_PERIPHERAL_OFFSET)

#define GPIOB_PERIPHERAL_OFFSET 	(0x00000400)
#define GPIOB_PERIPHERAL 			(AHB1_PERIPHERAL + GPIOB_PERIPHERAL_OFFSET)

#define GPIOC_PERIPHERAL_OFFSET 	(0x00000800)
#define GPIOC_PERIPHERAL 			(AHB1_PERIPHERAL + GPIOC_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET 		(0x00003800)
#define	RCC_PERIPHERAL				(AHB1_PERIPHERAL + RCC_PERIPHERAL_OFFSET)

enum State{
	OFF = 48, //int ascii 0
	ON = 49 // int ascii 1

};

#endif /* BASE_H_ */
