/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//include library
#include "stm32f4xx.h"

/*
  PA8 = red led
  PB10 = blue led
  PA7 = variable resistor X
  PA6 = Variable resistor y
  PC7 = Switch
*/
int main(void){

	//RCC - advance high performance bus enabling GPIO pot A pin 6,7,8, port B pin 10, and port C pin 7
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

	// PA8 - Red led
	GPIOA->MODER  |=  GPIO_MODER_MODER8_0;
	GPIOA->MODER  &= ~GPIO_MODER_MODER8_1; 									// bits [17:16] = 01 General purpose output mode
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT_8; 									//bit 8 = 0 Output push-pull (reset state)
	GPIOA->OSPEEDR |=  GPIO_OSPEEDR_OSPEEDR8_0 | GPIO_OSPEEDR_OSPEEDR8_1;	// bits [17:16] = 11  High speed
	GPIOA->PUPDR  &= ~GPIO_PUPDR_PUPDR8; 									// bits [19:18] = 00  No pull-up, no pull-down





	while(1){
		//if the button is pressed (IDR - input data register)
		// turn on the LED (BSRR)

		// if the button is not press
		//turn off the LED (BRR)
	}
}

