/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//include library
#include "stm32f4xx.h"

/*
  PA8 = red led
  PB10 = blue led
  PA7 = variable resistor X
  PA6 = Variable resistor y
  PC7 = Switch
*/
int main(void){

	//RCC - advance high performance bus enabling
	//GPIO pot A pin 6,7,8, port B pin 10, and port C pin 7
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

	// PA8 - Red led
	// bits 17:16 = 01 General purpose output mode
	GPIOA->MODER  |=  GPIO_MODER_MODER8_0;
	GPIOA->MODER  &= ~GPIO_MODER_MODER8_1;
	//output type register
	//bit 8 = 0 Output push-pull (reset state)
	GPIOA->OTYPER &= ~GPIO_OTYPER_OT_8;
	//output speed register
	// bits 17:16 = 11  High speed
	GPIOA->OSPEEDR |=  GPIO_OSPEEDR_OSPEEDR8_0 | GPIO_OSPEEDR_OSPEEDR8_1;
	//pull-up/pull-down register
	// bits 19:18 = 00  No pull-up, no pull-down
	GPIOA->PUPDR  &= ~GPIO_PUPDR_PUPDR8;

	//PB10 - Blue led
	GPIOB->MODER |= GPIO_MODER_MODER10_0;
	GPIOB->MODER &= ~GPIO_MODER_MODER10_1;
	GPIOB->OTYPER &= ~GPIO_OTYPER_OT_10;
	GPIOB->OSPEEDR |= GPIO_OSPEEDR_OSPEEDR10_0 | GPIO_OSPEEDR_OSPEEDR10_1;
	GPIOB->PUPDR  &= ~GPIO_PUPDR_PUPDR10;

	//PC7 - Switch input with pull up
	//Mode register
	GPIOC->MODER  &= ~GPIO_MODER_MODER7;       // input mode (00)
	//pull-up pull-down register
	GPIOC->PUPDR  |=  GPIO_PUPDR_PUPDR7_0;     // pull-up (01)
	GPIOC->PUPDR  &= ~GPIO_PUPDR_PUPDR7_1;


/*
	while(1){
		//if the button is pressed (IDR - input data register)
		// turn on the LED bit set/reset register(BSRR)
		if(GPIOC->IDR & GPIO_IDR_7){
			GPIOA->BSRR |= GPIO_BSRR_BS_8;
		} else{
			// if the button is not press
			//turn off the LED (BRR)
			GPIOA->BSRR |= GPIO_BSRR_BR_8;
		}


	}
*/
	//laching pin

	// initialized button pressed variable
	//note: "signed" can be value of -128 to 128
	//note: "unsigned" can be value of 0 to 255
	volatile char buttonPressed = 0;
	//initialized button pressed confidence level
	volatile int buttonPressedConfidenceLevel = 0;
	//initialized button released confidence level
	volatile int buttonReleasedConfidenceLevel = 0;
	//initialized confidence threshold level
	volatile int confidenceThreshold = 200;
	//LED lit state
	volatile char LEDState = 0;
	while(1){
			//if the button is pressed (IDR - input data register)
			// turn on the LED bit set/reset register(BSRR)
			if(GPIOC->IDR & GPIO_IDR_7){

				if (buttonPressed == 0){
					//increase the button pressed confidence level
					buttonPressedConfidenceLevel ++;
					buttonReleasedConfidenceLevel = 0;
					// once button confidence has passed the confidence level
					if(buttonPressedConfidenceLevel > confidenceThreshold){
						//toggle LEDs
						if (LEDState == 0){

							LEDState = 1;
							// on LED
							GPIOA->BSRR |= GPIO_BSRR_BS_8;

						}else{
							LEDState = 0;
							// off LED
							GPIOA->BSRR |= GPIO_BSRR_BR_8;

						}
						//update the button pressed variable to 1
						buttonPressed = 1;
					}
					else{
						buttonPressedConfidenceLevel ++;
						buttonReleasedConfidenceLevel = 0;
					}

				}


			} else{
				//increase tje button released confidence level
				//once the button release confidence level had been achieved
					//update the button pressed variable to 0

			}


		}
}

